spring:
  profiles: subject
server:
  port: 8031

---
spring:
  profiles: predicate
server:
  port: 8032

---
spring:
  profiles: object,regular
server:
  port: 8033

---
spring:
  profiles: object,christmas
server:
  port: 8034
